version: 2

build:
  on: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

# pip install hepfile with the docs optional requirements
# python -m pip install .[docs]
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true

mkdocs:
    configuration: mkdocs.yml
    fail_on_warning: false
