name: Documentation Issue
description: There is an issue in the documentation or example notebooks
title: "[Docs]: "
labels: ["documentation"]
assignees: []

body:
- type: markdown
  attributes:
    value: |
      Thanks for bringing up this issue! Please make sure you have checked closed issues and fill out the following information:

- type: input
  attributes:
    label: "Version of `hepfile`"
    description: |
      (please report if this is an issue with the examples)
    placeholder: "XX.YY.ZZ"
  validations:
    required: false

- type: input
  attributes:
    label: "Version of `NumPy`"
    description: |
      (please report if this is an issue with the examples)
    placeholder: "XX.YY.ZZ"
  validations:
    required: false

- type: input
  attributes:
    label: "Version of `h5py`"
    description: |
      (please report if this is an issue with the examples)
    placeholder: "XX.YY.ZZ"
  validations:
    required: false

- type: textarea
  id: other-packages
  attributes:
    label: "Other Relevant Package Versions"
    description: "Please list any other relevant package versions (ex. awkward, pandas, etc.)"

- type: textarea
  id: description
  attributes:
    label: "Describe the Documentation Issue"
    description: |
      "What seems wrong with the documentation? If it is an issue with the examples please provide a minimum working example."

- type: markdown
  attributes:
    value: "Thanks again for filling out this documentation issue report! We will get to it and respond as soon as possible!"
